import type {
  DiagnosisQuestionDefinition,
  DiagnosisSection,
} from '@/features/diagnosis/scoring/types';

export const diagnosisQuestionBank: DiagnosisQuestionDefinition[] = [
  {
    id: 'Q1',
    sectionId: 'brand_clarity',
    dimension: 'brand_clarity',
    type: 'single',
    weight: 2.0,
    question: '當客戶第一次問「你們到底是做什麼的？」時，團隊通常怎麼回答？',
    helperText: '看品牌定義是否能被團隊穩定複述，而不是只存在老闆腦中。',
    options: [
      { id: 'Q1_A', label: '每個人說法差很多，常常越解釋越模糊', score: 0 },
      { id: 'Q1_B', label: '大致說得出來，但不同人講法不太一致', score: 1 },
      { id: 'Q1_C', label: '已有固定說法，但還不夠精煉或有記憶點', score: 2 },
      { id: 'Q1_D', label: '能用一句清楚說明，且團隊對外說法一致', score: 4 },
    ],
  },
  {
    id: 'Q2',
    sectionId: 'brand_clarity',
    dimension: 'brand_clarity',
    type: 'binary',
    weight: 1.5,
    question: '目前你們是否有明確定義的核心客群，且團隊實際依此執行？',
    helperText: '這題直接看客群理解是否真的進入內容、行銷與銷售決策。',
    options: [
      { id: 'Q2_A', label: '沒有，或只有口頭認知，實際上沒有依此執行', score: 0 },
      { id: 'Q2_B', label: '有，而且行銷、內容、銷售都以此作為判斷基準', score: 4 },
    ],
  },
  {
    id: 'Q3',
    sectionId: 'brand_clarity',
    dimension: 'brand_clarity',
    type: 'scenario',
    weight: 1.5,
    question: '如果今天要讓一位新進同事在 30 分鐘內理解品牌定位，你們最接近哪種狀態？',
    helperText: '看品牌知識是否被整理成可傳承的系統，而非臨場解釋。',
    options: [
      { id: 'Q3_A', label: '沒有可交付資料，只能靠老闆口頭說明', score: 0 },
      { id: 'Q3_B', label: '有一些零散文件，但看完仍難掌握重點', score: 1 },
      { id: 'Q3_C', label: '有整理過品牌介紹，但不足以直接拿來對外使用', score: 2 },
      { id: 'Q3_D', label: '有清楚的品牌定位文件，新人可快速理解並沿用', score: 4 },
    ],
  },
  {
    id: 'Q4',
    sectionId: 'brand_clarity',
    dimension: 'brand_clarity',
    type: 'single',
    weight: 1.0,
    question: '你們的產品或服務頁面，是否清楚說明「適合誰、不適合誰」？',
    helperText: '這題看品牌是否有能力主動篩選客戶，而不是對所有人說話。',
    options: [
      { id: 'Q4_A', label: '幾乎沒有寫，誰看都像在講所有人', score: 0 },
      { id: 'Q4_B', label: '有提到目標客群，但很籠統', score: 1 },
      { id: 'Q4_C', label: '大致能看出適合對象，但不夠直接', score: 2 },
      { id: 'Q4_D', label: '很清楚界定適合與不適合的人，降低誤會', score: 4 },
    ],
  },
  {
    id: 'Q5',
    sectionId: 'visual_consistency',
    dimension: 'visual_consistency',
    type: 'single',
    weight: 1.0,
    question: '當客戶在 IG、官網、菜單、名片之間切換時，品牌視覺的一致程度最接近哪種狀態？',
    helperText: '看不同接觸點是否呈現同一個品牌，而非一組零散素材。',
    options: [
      { id: 'Q5_A', label: '看起來像不同品牌做的', score: 0 },
      { id: 'Q5_B', label: '有些元素相同，但整體風格仍不穩', score: 1 },
      { id: 'Q5_C', label: '大致一致，偶爾會出現風格偏差', score: 2 },
      { id: 'Q5_D', label: '主要接觸點高度一致，一看就知道是同一品牌', score: 4 },
    ],
  },
  {
    id: 'Q6',
    sectionId: 'visual_consistency',
    dimension: 'visual_consistency',
    type: 'binary',
    weight: 1.5,
    question: '你們是否有實際可使用的品牌視覺規範，包含 logo、字體、色彩、版型或素材原則？',
    helperText: '這題不問有沒有設計稿，而是問是否真的有規範可被他人沿用。',
    options: [
      { id: 'Q6_A', label: '沒有，或只有設計檔，沒有規範文件', score: 0 },
      { id: 'Q6_B', label: '有，而且內部與外包都能依規範穩定執行', score: 4 },
    ],
  },
  {
    id: 'Q7',
    sectionId: 'visual_consistency',
    dimension: 'visual_consistency',
    type: 'scenario',
    weight: 1.0,
    question: '如果明天臨時要做一張促銷圖，你們最可能怎麼產出？',
    helperText: '這題直接檢查品牌系統在日常執行中的可複製性。',
    options: [
      { id: 'Q7_A', label: '誰方便誰做，畫面品質與品牌感常常不穩', score: 0 },
      { id: 'Q7_B', label: '會參考舊圖，但每次還是靠個人感覺調整', score: 1 },
      { id: 'Q7_C', label: '有模板可參考，品質大多穩定', score: 2 },
      { id: 'Q7_D', label: '有清楚模板與規則，任何人做都能維持品牌一致', score: 4 },
    ],
  },
  {
    id: 'Q8',
    sectionId: 'differentiation',
    dimension: 'differentiation',
    type: 'single',
    weight: 2.0,
    question: '當客戶比較你和 2 到 3 個競品時，你們的差異通常呈現在哪裡？',
    helperText: '差異化若只剩價格，品牌通常很難累積長期優勢。',
    options: [
      { id: 'Q8_A', label: '主要只能比價格或促銷', score: 0 },
      { id: 'Q8_B', label: '有一些不同，但多半是自己覺得不同，客戶未必感受到', score: 1 },
      { id: 'Q8_C', label: '客戶能感受到部分差異，但還不夠鮮明', score: 2 },
      { id: 'Q8_D', label: '差異點清楚具體，客戶能直接說出你們與別人的不同', score: 4 },
    ],
  },
  {
    id: 'Q9',
    sectionId: 'differentiation',
    dimension: 'differentiation',
    type: 'binary',
    weight: 2.0,
    question: '如果拿掉品牌名稱與 logo，你們的文案、主張或呈現方式，客戶還能辨識出是你們嗎？',
    helperText: '這題直接測試品牌辨識度，而不是自我感覺良好。',
    options: [
      { id: 'Q9_A', label: '大多不行，和同業放在一起很容易混在一起', score: 0 },
      { id: 'Q9_B', label: '有機會，因為語言、主張或呈現方式已具有辨識度', score: 4 },
    ],
  },
  {
    id: 'Q10',
    sectionId: 'differentiation',
    dimension: 'differentiation',
    type: 'scenario',
    weight: 1.5,
    question: '如果現在要寫一則廣告標題，你們最接近哪種狀態？',
    helperText: '這題看品牌主張是否銳利到能直接被轉成市場溝通。',
    options: [
      { id: 'Q10_A', label: '常使用任何同業都能套用的空泛說法', score: 0 },
      { id: 'Q10_B', label: '偶爾能帶出特色，但不夠穩定', score: 1 },
      { id: 'Q10_C', label: '大多能寫出品牌特色，但還不夠犀利', score: 2 },
      { id: 'Q10_D', label: '能穩定寫出只有你們品牌才說得出的主張', score: 4 },
    ],
  },
  {
    id: 'Q11',
    sectionId: 'differentiation',
    dimension: 'differentiation',
    type: 'single',
    weight: 1.0,
    question: '你們目前對外最常用的品牌主張，與競品相比屬於哪種狀態？',
    helperText: '這題檢查對外主張是否真的能形成市場區隔。',
    options: [
      { id: 'Q11_A', label: '幾乎和市場常見說法重疊', score: 0 },
      { id: 'Q11_B', label: '有些不同，但仍偏通用', score: 1 },
      { id: 'Q11_C', label: '有明顯區隔，但仍可再聚焦', score: 2 },
      { id: 'Q11_D', label: '高度聚焦且具辨識度，競品不容易直接複製', score: 4 },
    ],
  },
  {
    id: 'Q12',
    sectionId: 'conversion_trust',
    dimension: 'conversion_trust',
    type: 'single',
    weight: 2.0,
    question: '當新客戶第一次進到官網、社群或門市頁面時，能否快速找到「為什麼值得相信你」的證據？',
    helperText: '這題檢查信任證據是否已經進入實際轉換流程，而非只有品牌形象。',
    options: [
      { id: 'Q12_A', label: '幾乎沒有，只有產品資訊或空泛宣稱', score: 0 },
      { id: 'Q12_B', label: '有少量證據，但分散且不夠明顯', score: 1 },
      { id: 'Q12_C', label: '有基本信任證據，例如案例、評價、保證，但呈現仍可加強', score: 2 },
      { id: 'Q12_D', label: '信任證據完整且醒目，能有效支撐轉換', score: 4 },
    ],
  },
  {
    id: 'Q13',
    sectionId: 'conversion_trust',
    dimension: 'conversion_trust',
    type: 'binary',
    weight: 2.0,
    question: '你們是否清楚知道客戶最後不下單的主要原因，並且已在頁面或銷售流程中主動處理？',
    helperText: '這題看品牌是否真的理解轉換阻力，而非只把問題歸因於流量不足。',
    options: [
      { id: 'Q13_A', label: '不知道，或知道但沒有具體處理', score: 0 },
      { id: 'Q13_B', label: '知道，而且已在頁面、話術或流程中主動處理', score: 4 },
    ],
  },
  {
    id: 'Q14',
    sectionId: 'conversion_trust',
    dimension: 'conversion_trust',
    type: 'scenario',
    weight: 1.5,
    question: '如果客戶今天看完你們的品牌頁面卻沒有留下詢問，最接近現況的是哪一種？',
    helperText: '這題檢查轉換阻力是否出在價值、信任或下一步行動設計。',
    options: [
      { id: 'Q14_A', label: '頁面沒有清楚下一步，也缺乏讓人放心行動的理由', score: 0 },
      { id: 'Q14_B', label: '有 CTA，但價值與信任證據不足，客戶還是猶豫', score: 1 },
      { id: 'Q14_C', label: '價值、流程與 CTA 大致清楚，但仍有摩擦點', score: 2 },
      { id: 'Q14_D', label: '價值主張、信任證據與下一步都很清楚，轉換阻力低', score: 4 },
    ],
  },
];

export const diagnosisSections: DiagnosisSection[] = [
  {
    id: 'brand_clarity',
    title: '品牌清晰度',
    description: '檢查品牌定位、客群定義與對外說法是否清楚。',
    questionIds: ['Q1', 'Q2', 'Q3', 'Q4'],
  },
  {
    id: 'visual_consistency',
    title: '視覺一致性',
    description: '檢查品牌視覺是否具備穩定規範與可複製性。',
    questionIds: ['Q5', 'Q6', 'Q7'],
  },
  {
    id: 'differentiation',
    title: '市場差異',
    description: '檢查品牌是否具有可感知的區隔與辨識度。',
    questionIds: ['Q8', 'Q9', 'Q10', 'Q11'],
  },
  {
    id: 'conversion_trust',
    title: '轉換與信任',
    description: '檢查品牌是否能有效建立信任並推動詢問或成交。',
    questionIds: ['Q12', 'Q13', 'Q14'],
  },
];
